-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity test_scalaire_test_scalaire_Pipeline_VITIS_LOOP_23_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_bus_res_AWVALID : OUT STD_LOGIC;
    m_axi_bus_res_AWREADY : IN STD_LOGIC;
    m_axi_bus_res_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_bus_res_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_bus_res_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_bus_res_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_bus_res_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_bus_res_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_bus_res_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_bus_res_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_bus_res_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_bus_res_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_bus_res_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_bus_res_WVALID : OUT STD_LOGIC;
    m_axi_bus_res_WREADY : IN STD_LOGIC;
    m_axi_bus_res_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_bus_res_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_bus_res_WLAST : OUT STD_LOGIC;
    m_axi_bus_res_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_bus_res_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_bus_res_ARVALID : OUT STD_LOGIC;
    m_axi_bus_res_ARREADY : IN STD_LOGIC;
    m_axi_bus_res_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_bus_res_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_bus_res_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_bus_res_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_bus_res_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_bus_res_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_bus_res_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_bus_res_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_bus_res_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_bus_res_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_bus_res_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_bus_res_RVALID : IN STD_LOGIC;
    m_axi_bus_res_RREADY : OUT STD_LOGIC;
    m_axi_bus_res_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_bus_res_RLAST : IN STD_LOGIC;
    m_axi_bus_res_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_bus_res_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_bus_res_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_bus_res_BVALID : IN STD_LOGIC;
    m_axi_bus_res_BREADY : OUT STD_LOGIC;
    m_axi_bus_res_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_bus_res_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_bus_res_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln23 : IN STD_LOGIC_VECTOR (29 downto 0);
    bitcast_ln25 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of test_scalaire_test_scalaire_Pipeline_VITIS_LOOP_23_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln23_fu_92_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal bus_res_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal i_fu_50 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln23_fu_98_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component test_scalaire_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component test_scalaire_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_50_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln23_fu_92_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_50 <= add_ln23_fu_98_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_50 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln23_fu_98_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv4_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_bus_res_WREADY)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_bus_res_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_bus_res_WREADY)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_bus_res_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln23_fu_92_p2)
    begin
        if (((icmp_ln23_fu_92_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_50, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_50;
        end if; 
    end process;


    bus_res_blk_n_W_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_bus_res_WREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bus_res_blk_n_W <= m_axi_bus_res_WREADY;
        else 
            bus_res_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln23_fu_92_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv4_8) else "0";
    m_axi_bus_res_ARADDR <= ap_const_lv32_0;
    m_axi_bus_res_ARBURST <= ap_const_lv2_0;
    m_axi_bus_res_ARCACHE <= ap_const_lv4_0;
    m_axi_bus_res_ARID <= ap_const_lv1_0;
    m_axi_bus_res_ARLEN <= ap_const_lv32_0;
    m_axi_bus_res_ARLOCK <= ap_const_lv2_0;
    m_axi_bus_res_ARPROT <= ap_const_lv3_0;
    m_axi_bus_res_ARQOS <= ap_const_lv4_0;
    m_axi_bus_res_ARREGION <= ap_const_lv4_0;
    m_axi_bus_res_ARSIZE <= ap_const_lv3_0;
    m_axi_bus_res_ARUSER <= ap_const_lv1_0;
    m_axi_bus_res_ARVALID <= ap_const_logic_0;
    m_axi_bus_res_AWADDR <= ap_const_lv32_0;
    m_axi_bus_res_AWBURST <= ap_const_lv2_0;
    m_axi_bus_res_AWCACHE <= ap_const_lv4_0;
    m_axi_bus_res_AWID <= ap_const_lv1_0;
    m_axi_bus_res_AWLEN <= ap_const_lv32_0;
    m_axi_bus_res_AWLOCK <= ap_const_lv2_0;
    m_axi_bus_res_AWPROT <= ap_const_lv3_0;
    m_axi_bus_res_AWQOS <= ap_const_lv4_0;
    m_axi_bus_res_AWREGION <= ap_const_lv4_0;
    m_axi_bus_res_AWSIZE <= ap_const_lv3_0;
    m_axi_bus_res_AWUSER <= ap_const_lv1_0;
    m_axi_bus_res_AWVALID <= ap_const_logic_0;
    m_axi_bus_res_BREADY <= ap_const_logic_0;
    m_axi_bus_res_RREADY <= ap_const_logic_0;
    m_axi_bus_res_WDATA <= bitcast_ln25;
    m_axi_bus_res_WID <= ap_const_lv1_0;
    m_axi_bus_res_WLAST <= ap_const_logic_0;
    m_axi_bus_res_WSTRB <= ap_const_lv4_F;
    m_axi_bus_res_WUSER <= ap_const_lv1_0;

    m_axi_bus_res_WVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axi_bus_res_WVALID <= ap_const_logic_1;
        else 
            m_axi_bus_res_WVALID <= ap_const_logic_0;
        end if; 
    end process;

end behav;
