# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/projet_m2/git/zynq-oc-analysis/mk1/mk1_implement/mk1_implement.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_2/design_1_axi_bram_ctrl_0_2.xci
# IP: The module: 'design_1_axi_bram_ctrl_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/projet_m2/git/zynq-oc-analysis/mk1/mk1_implement/mk1_implement.gen/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_2/design_1_axi_bram_ctrl_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_bram_ctrl_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: F:/projet_m2/git/zynq-oc-analysis/mk1/mk1_implement/mk1_implement.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_2/design_1_axi_bram_ctrl_0_2.xci
# IP: The module: 'design_1_axi_bram_ctrl_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/projet_m2/git/zynq-oc-analysis/mk1/mk1_implement/mk1_implement.gen/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_2/design_1_axi_bram_ctrl_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_bram_ctrl_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
