// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="test_scalaire_test_scalaire,hls_ip_2021_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=1558,HLS_SYN_TPT=none,HLS_SYN_MEM=12,HLS_SYN_DSP=0,HLS_SYN_FF=2320,HLS_SYN_LUT=3215,HLS_VERSION=2021_1}" *)

module test_scalaire (
        ap_clk,
        ap_rst_n,
        m_axi_bus_A_AWVALID,
        m_axi_bus_A_AWREADY,
        m_axi_bus_A_AWADDR,
        m_axi_bus_A_AWID,
        m_axi_bus_A_AWLEN,
        m_axi_bus_A_AWSIZE,
        m_axi_bus_A_AWBURST,
        m_axi_bus_A_AWLOCK,
        m_axi_bus_A_AWCACHE,
        m_axi_bus_A_AWPROT,
        m_axi_bus_A_AWQOS,
        m_axi_bus_A_AWREGION,
        m_axi_bus_A_AWUSER,
        m_axi_bus_A_WVALID,
        m_axi_bus_A_WREADY,
        m_axi_bus_A_WDATA,
        m_axi_bus_A_WSTRB,
        m_axi_bus_A_WLAST,
        m_axi_bus_A_WID,
        m_axi_bus_A_WUSER,
        m_axi_bus_A_ARVALID,
        m_axi_bus_A_ARREADY,
        m_axi_bus_A_ARADDR,
        m_axi_bus_A_ARID,
        m_axi_bus_A_ARLEN,
        m_axi_bus_A_ARSIZE,
        m_axi_bus_A_ARBURST,
        m_axi_bus_A_ARLOCK,
        m_axi_bus_A_ARCACHE,
        m_axi_bus_A_ARPROT,
        m_axi_bus_A_ARQOS,
        m_axi_bus_A_ARREGION,
        m_axi_bus_A_ARUSER,
        m_axi_bus_A_RVALID,
        m_axi_bus_A_RREADY,
        m_axi_bus_A_RDATA,
        m_axi_bus_A_RLAST,
        m_axi_bus_A_RID,
        m_axi_bus_A_RUSER,
        m_axi_bus_A_RRESP,
        m_axi_bus_A_BVALID,
        m_axi_bus_A_BREADY,
        m_axi_bus_A_BRESP,
        m_axi_bus_A_BID,
        m_axi_bus_A_BUSER,
        m_axi_bus_B_AWVALID,
        m_axi_bus_B_AWREADY,
        m_axi_bus_B_AWADDR,
        m_axi_bus_B_AWID,
        m_axi_bus_B_AWLEN,
        m_axi_bus_B_AWSIZE,
        m_axi_bus_B_AWBURST,
        m_axi_bus_B_AWLOCK,
        m_axi_bus_B_AWCACHE,
        m_axi_bus_B_AWPROT,
        m_axi_bus_B_AWQOS,
        m_axi_bus_B_AWREGION,
        m_axi_bus_B_AWUSER,
        m_axi_bus_B_WVALID,
        m_axi_bus_B_WREADY,
        m_axi_bus_B_WDATA,
        m_axi_bus_B_WSTRB,
        m_axi_bus_B_WLAST,
        m_axi_bus_B_WID,
        m_axi_bus_B_WUSER,
        m_axi_bus_B_ARVALID,
        m_axi_bus_B_ARREADY,
        m_axi_bus_B_ARADDR,
        m_axi_bus_B_ARID,
        m_axi_bus_B_ARLEN,
        m_axi_bus_B_ARSIZE,
        m_axi_bus_B_ARBURST,
        m_axi_bus_B_ARLOCK,
        m_axi_bus_B_ARCACHE,
        m_axi_bus_B_ARPROT,
        m_axi_bus_B_ARQOS,
        m_axi_bus_B_ARREGION,
        m_axi_bus_B_ARUSER,
        m_axi_bus_B_RVALID,
        m_axi_bus_B_RREADY,
        m_axi_bus_B_RDATA,
        m_axi_bus_B_RLAST,
        m_axi_bus_B_RID,
        m_axi_bus_B_RUSER,
        m_axi_bus_B_RRESP,
        m_axi_bus_B_BVALID,
        m_axi_bus_B_BREADY,
        m_axi_bus_B_BRESP,
        m_axi_bus_B_BID,
        m_axi_bus_B_BUSER,
        m_axi_bus_res_AWVALID,
        m_axi_bus_res_AWREADY,
        m_axi_bus_res_AWADDR,
        m_axi_bus_res_AWID,
        m_axi_bus_res_AWLEN,
        m_axi_bus_res_AWSIZE,
        m_axi_bus_res_AWBURST,
        m_axi_bus_res_AWLOCK,
        m_axi_bus_res_AWCACHE,
        m_axi_bus_res_AWPROT,
        m_axi_bus_res_AWQOS,
        m_axi_bus_res_AWREGION,
        m_axi_bus_res_AWUSER,
        m_axi_bus_res_WVALID,
        m_axi_bus_res_WREADY,
        m_axi_bus_res_WDATA,
        m_axi_bus_res_WSTRB,
        m_axi_bus_res_WLAST,
        m_axi_bus_res_WID,
        m_axi_bus_res_WUSER,
        m_axi_bus_res_ARVALID,
        m_axi_bus_res_ARREADY,
        m_axi_bus_res_ARADDR,
        m_axi_bus_res_ARID,
        m_axi_bus_res_ARLEN,
        m_axi_bus_res_ARSIZE,
        m_axi_bus_res_ARBURST,
        m_axi_bus_res_ARLOCK,
        m_axi_bus_res_ARCACHE,
        m_axi_bus_res_ARPROT,
        m_axi_bus_res_ARQOS,
        m_axi_bus_res_ARREGION,
        m_axi_bus_res_ARUSER,
        m_axi_bus_res_RVALID,
        m_axi_bus_res_RREADY,
        m_axi_bus_res_RDATA,
        m_axi_bus_res_RLAST,
        m_axi_bus_res_RID,
        m_axi_bus_res_RUSER,
        m_axi_bus_res_RRESP,
        m_axi_bus_res_BVALID,
        m_axi_bus_res_BREADY,
        m_axi_bus_res_BRESP,
        m_axi_bus_res_BID,
        m_axi_bus_res_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 16'd1;
parameter    ap_ST_fsm_state2 = 16'd2;
parameter    ap_ST_fsm_state3 = 16'd4;
parameter    ap_ST_fsm_state4 = 16'd8;
parameter    ap_ST_fsm_state5 = 16'd16;
parameter    ap_ST_fsm_state6 = 16'd32;
parameter    ap_ST_fsm_state7 = 16'd64;
parameter    ap_ST_fsm_state8 = 16'd128;
parameter    ap_ST_fsm_state9 = 16'd256;
parameter    ap_ST_fsm_state10 = 16'd512;
parameter    ap_ST_fsm_state11 = 16'd1024;
parameter    ap_ST_fsm_state12 = 16'd2048;
parameter    ap_ST_fsm_state13 = 16'd4096;
parameter    ap_ST_fsm_state14 = 16'd8192;
parameter    ap_ST_fsm_state15 = 16'd16384;
parameter    ap_ST_fsm_state16 = 16'd32768;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_BUS_A_ID_WIDTH = 1;
parameter    C_M_AXI_BUS_A_ADDR_WIDTH = 32;
parameter    C_M_AXI_BUS_A_DATA_WIDTH = 32;
parameter    C_M_AXI_BUS_A_AWUSER_WIDTH = 1;
parameter    C_M_AXI_BUS_A_ARUSER_WIDTH = 1;
parameter    C_M_AXI_BUS_A_WUSER_WIDTH = 1;
parameter    C_M_AXI_BUS_A_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUS_A_BUSER_WIDTH = 1;
parameter    C_M_AXI_BUS_A_USER_VALUE = 0;
parameter    C_M_AXI_BUS_A_PROT_VALUE = 0;
parameter    C_M_AXI_BUS_A_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_BUS_B_ID_WIDTH = 1;
parameter    C_M_AXI_BUS_B_ADDR_WIDTH = 32;
parameter    C_M_AXI_BUS_B_DATA_WIDTH = 32;
parameter    C_M_AXI_BUS_B_AWUSER_WIDTH = 1;
parameter    C_M_AXI_BUS_B_ARUSER_WIDTH = 1;
parameter    C_M_AXI_BUS_B_WUSER_WIDTH = 1;
parameter    C_M_AXI_BUS_B_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUS_B_BUSER_WIDTH = 1;
parameter    C_M_AXI_BUS_B_USER_VALUE = 0;
parameter    C_M_AXI_BUS_B_PROT_VALUE = 0;
parameter    C_M_AXI_BUS_B_CACHE_VALUE = 3;
parameter    C_M_AXI_BUS_RES_ID_WIDTH = 1;
parameter    C_M_AXI_BUS_RES_ADDR_WIDTH = 32;
parameter    C_M_AXI_BUS_RES_DATA_WIDTH = 32;
parameter    C_M_AXI_BUS_RES_AWUSER_WIDTH = 1;
parameter    C_M_AXI_BUS_RES_ARUSER_WIDTH = 1;
parameter    C_M_AXI_BUS_RES_WUSER_WIDTH = 1;
parameter    C_M_AXI_BUS_RES_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUS_RES_BUSER_WIDTH = 1;
parameter    C_M_AXI_BUS_RES_USER_VALUE = 0;
parameter    C_M_AXI_BUS_RES_PROT_VALUE = 0;
parameter    C_M_AXI_BUS_RES_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_BUS_A_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_BUS_B_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_BUS_RES_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_bus_A_AWVALID;
input   m_axi_bus_A_AWREADY;
output  [C_M_AXI_BUS_A_ADDR_WIDTH - 1:0] m_axi_bus_A_AWADDR;
output  [C_M_AXI_BUS_A_ID_WIDTH - 1:0] m_axi_bus_A_AWID;
output  [7:0] m_axi_bus_A_AWLEN;
output  [2:0] m_axi_bus_A_AWSIZE;
output  [1:0] m_axi_bus_A_AWBURST;
output  [1:0] m_axi_bus_A_AWLOCK;
output  [3:0] m_axi_bus_A_AWCACHE;
output  [2:0] m_axi_bus_A_AWPROT;
output  [3:0] m_axi_bus_A_AWQOS;
output  [3:0] m_axi_bus_A_AWREGION;
output  [C_M_AXI_BUS_A_AWUSER_WIDTH - 1:0] m_axi_bus_A_AWUSER;
output   m_axi_bus_A_WVALID;
input   m_axi_bus_A_WREADY;
output  [C_M_AXI_BUS_A_DATA_WIDTH - 1:0] m_axi_bus_A_WDATA;
output  [C_M_AXI_BUS_A_WSTRB_WIDTH - 1:0] m_axi_bus_A_WSTRB;
output   m_axi_bus_A_WLAST;
output  [C_M_AXI_BUS_A_ID_WIDTH - 1:0] m_axi_bus_A_WID;
output  [C_M_AXI_BUS_A_WUSER_WIDTH - 1:0] m_axi_bus_A_WUSER;
output   m_axi_bus_A_ARVALID;
input   m_axi_bus_A_ARREADY;
output  [C_M_AXI_BUS_A_ADDR_WIDTH - 1:0] m_axi_bus_A_ARADDR;
output  [C_M_AXI_BUS_A_ID_WIDTH - 1:0] m_axi_bus_A_ARID;
output  [7:0] m_axi_bus_A_ARLEN;
output  [2:0] m_axi_bus_A_ARSIZE;
output  [1:0] m_axi_bus_A_ARBURST;
output  [1:0] m_axi_bus_A_ARLOCK;
output  [3:0] m_axi_bus_A_ARCACHE;
output  [2:0] m_axi_bus_A_ARPROT;
output  [3:0] m_axi_bus_A_ARQOS;
output  [3:0] m_axi_bus_A_ARREGION;
output  [C_M_AXI_BUS_A_ARUSER_WIDTH - 1:0] m_axi_bus_A_ARUSER;
input   m_axi_bus_A_RVALID;
output   m_axi_bus_A_RREADY;
input  [C_M_AXI_BUS_A_DATA_WIDTH - 1:0] m_axi_bus_A_RDATA;
input   m_axi_bus_A_RLAST;
input  [C_M_AXI_BUS_A_ID_WIDTH - 1:0] m_axi_bus_A_RID;
input  [C_M_AXI_BUS_A_RUSER_WIDTH - 1:0] m_axi_bus_A_RUSER;
input  [1:0] m_axi_bus_A_RRESP;
input   m_axi_bus_A_BVALID;
output   m_axi_bus_A_BREADY;
input  [1:0] m_axi_bus_A_BRESP;
input  [C_M_AXI_BUS_A_ID_WIDTH - 1:0] m_axi_bus_A_BID;
input  [C_M_AXI_BUS_A_BUSER_WIDTH - 1:0] m_axi_bus_A_BUSER;
output   m_axi_bus_B_AWVALID;
input   m_axi_bus_B_AWREADY;
output  [C_M_AXI_BUS_B_ADDR_WIDTH - 1:0] m_axi_bus_B_AWADDR;
output  [C_M_AXI_BUS_B_ID_WIDTH - 1:0] m_axi_bus_B_AWID;
output  [7:0] m_axi_bus_B_AWLEN;
output  [2:0] m_axi_bus_B_AWSIZE;
output  [1:0] m_axi_bus_B_AWBURST;
output  [1:0] m_axi_bus_B_AWLOCK;
output  [3:0] m_axi_bus_B_AWCACHE;
output  [2:0] m_axi_bus_B_AWPROT;
output  [3:0] m_axi_bus_B_AWQOS;
output  [3:0] m_axi_bus_B_AWREGION;
output  [C_M_AXI_BUS_B_AWUSER_WIDTH - 1:0] m_axi_bus_B_AWUSER;
output   m_axi_bus_B_WVALID;
input   m_axi_bus_B_WREADY;
output  [C_M_AXI_BUS_B_DATA_WIDTH - 1:0] m_axi_bus_B_WDATA;
output  [C_M_AXI_BUS_B_WSTRB_WIDTH - 1:0] m_axi_bus_B_WSTRB;
output   m_axi_bus_B_WLAST;
output  [C_M_AXI_BUS_B_ID_WIDTH - 1:0] m_axi_bus_B_WID;
output  [C_M_AXI_BUS_B_WUSER_WIDTH - 1:0] m_axi_bus_B_WUSER;
output   m_axi_bus_B_ARVALID;
input   m_axi_bus_B_ARREADY;
output  [C_M_AXI_BUS_B_ADDR_WIDTH - 1:0] m_axi_bus_B_ARADDR;
output  [C_M_AXI_BUS_B_ID_WIDTH - 1:0] m_axi_bus_B_ARID;
output  [7:0] m_axi_bus_B_ARLEN;
output  [2:0] m_axi_bus_B_ARSIZE;
output  [1:0] m_axi_bus_B_ARBURST;
output  [1:0] m_axi_bus_B_ARLOCK;
output  [3:0] m_axi_bus_B_ARCACHE;
output  [2:0] m_axi_bus_B_ARPROT;
output  [3:0] m_axi_bus_B_ARQOS;
output  [3:0] m_axi_bus_B_ARREGION;
output  [C_M_AXI_BUS_B_ARUSER_WIDTH - 1:0] m_axi_bus_B_ARUSER;
input   m_axi_bus_B_RVALID;
output   m_axi_bus_B_RREADY;
input  [C_M_AXI_BUS_B_DATA_WIDTH - 1:0] m_axi_bus_B_RDATA;
input   m_axi_bus_B_RLAST;
input  [C_M_AXI_BUS_B_ID_WIDTH - 1:0] m_axi_bus_B_RID;
input  [C_M_AXI_BUS_B_RUSER_WIDTH - 1:0] m_axi_bus_B_RUSER;
input  [1:0] m_axi_bus_B_RRESP;
input   m_axi_bus_B_BVALID;
output   m_axi_bus_B_BREADY;
input  [1:0] m_axi_bus_B_BRESP;
input  [C_M_AXI_BUS_B_ID_WIDTH - 1:0] m_axi_bus_B_BID;
input  [C_M_AXI_BUS_B_BUSER_WIDTH - 1:0] m_axi_bus_B_BUSER;
output   m_axi_bus_res_AWVALID;
input   m_axi_bus_res_AWREADY;
output  [C_M_AXI_BUS_RES_ADDR_WIDTH - 1:0] m_axi_bus_res_AWADDR;
output  [C_M_AXI_BUS_RES_ID_WIDTH - 1:0] m_axi_bus_res_AWID;
output  [7:0] m_axi_bus_res_AWLEN;
output  [2:0] m_axi_bus_res_AWSIZE;
output  [1:0] m_axi_bus_res_AWBURST;
output  [1:0] m_axi_bus_res_AWLOCK;
output  [3:0] m_axi_bus_res_AWCACHE;
output  [2:0] m_axi_bus_res_AWPROT;
output  [3:0] m_axi_bus_res_AWQOS;
output  [3:0] m_axi_bus_res_AWREGION;
output  [C_M_AXI_BUS_RES_AWUSER_WIDTH - 1:0] m_axi_bus_res_AWUSER;
output   m_axi_bus_res_WVALID;
input   m_axi_bus_res_WREADY;
output  [C_M_AXI_BUS_RES_DATA_WIDTH - 1:0] m_axi_bus_res_WDATA;
output  [C_M_AXI_BUS_RES_WSTRB_WIDTH - 1:0] m_axi_bus_res_WSTRB;
output   m_axi_bus_res_WLAST;
output  [C_M_AXI_BUS_RES_ID_WIDTH - 1:0] m_axi_bus_res_WID;
output  [C_M_AXI_BUS_RES_WUSER_WIDTH - 1:0] m_axi_bus_res_WUSER;
output   m_axi_bus_res_ARVALID;
input   m_axi_bus_res_ARREADY;
output  [C_M_AXI_BUS_RES_ADDR_WIDTH - 1:0] m_axi_bus_res_ARADDR;
output  [C_M_AXI_BUS_RES_ID_WIDTH - 1:0] m_axi_bus_res_ARID;
output  [7:0] m_axi_bus_res_ARLEN;
output  [2:0] m_axi_bus_res_ARSIZE;
output  [1:0] m_axi_bus_res_ARBURST;
output  [1:0] m_axi_bus_res_ARLOCK;
output  [3:0] m_axi_bus_res_ARCACHE;
output  [2:0] m_axi_bus_res_ARPROT;
output  [3:0] m_axi_bus_res_ARQOS;
output  [3:0] m_axi_bus_res_ARREGION;
output  [C_M_AXI_BUS_RES_ARUSER_WIDTH - 1:0] m_axi_bus_res_ARUSER;
input   m_axi_bus_res_RVALID;
output   m_axi_bus_res_RREADY;
input  [C_M_AXI_BUS_RES_DATA_WIDTH - 1:0] m_axi_bus_res_RDATA;
input   m_axi_bus_res_RLAST;
input  [C_M_AXI_BUS_RES_ID_WIDTH - 1:0] m_axi_bus_res_RID;
input  [C_M_AXI_BUS_RES_RUSER_WIDTH - 1:0] m_axi_bus_res_RUSER;
input  [1:0] m_axi_bus_res_RRESP;
input   m_axi_bus_res_BVALID;
output   m_axi_bus_res_BREADY;
input  [1:0] m_axi_bus_res_BRESP;
input  [C_M_AXI_BUS_RES_ID_WIDTH - 1:0] m_axi_bus_res_BID;
input  [C_M_AXI_BUS_RES_BUSER_WIDTH - 1:0] m_axi_bus_res_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] A;
wire   [31:0] B;
wire   [31:0] res;
reg    bus_A_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    bus_B_blk_n_AR;
reg    bus_res_blk_n_AW;
wire    ap_CS_fsm_state10;
reg    bus_res_blk_n_W;
wire    ap_CS_fsm_state11;
reg    bus_res_blk_n_B;
wire    ap_CS_fsm_state16;
reg   [29:0] trunc_ln_reg_211;
reg   [29:0] trunc_ln14_1_reg_217;
reg   [29:0] trunc_ln1_reg_223;
wire    grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_ap_start;
wire    grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_ap_done;
wire    grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_ap_idle;
wire    grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_ap_ready;
wire    grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWVALID;
wire   [31:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWADDR;
wire   [0:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWID;
wire   [31:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWLEN;
wire   [2:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWSIZE;
wire   [1:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWBURST;
wire   [1:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWLOCK;
wire   [3:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWCACHE;
wire   [2:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWPROT;
wire   [3:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWQOS;
wire   [3:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWREGION;
wire   [0:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWUSER;
wire    grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_WVALID;
wire   [31:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_WDATA;
wire   [3:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_WSTRB;
wire    grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_WLAST;
wire   [0:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_WID;
wire   [0:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_WUSER;
wire    grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARVALID;
wire   [31:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARADDR;
wire   [0:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARID;
wire   [31:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARLEN;
wire   [2:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARSIZE;
wire   [1:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARBURST;
wire   [1:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARLOCK;
wire   [3:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARCACHE;
wire   [2:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARPROT;
wire   [3:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARQOS;
wire   [3:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARREGION;
wire   [0:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARUSER;
wire    grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_RREADY;
wire    grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_BREADY;
wire    grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWVALID;
wire   [31:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWADDR;
wire   [0:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWID;
wire   [31:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWLEN;
wire   [2:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWSIZE;
wire   [1:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWBURST;
wire   [1:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWLOCK;
wire   [3:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWCACHE;
wire   [2:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWPROT;
wire   [3:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWQOS;
wire   [3:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWREGION;
wire   [0:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWUSER;
wire    grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_WVALID;
wire   [31:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_WDATA;
wire   [3:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_WSTRB;
wire    grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_WLAST;
wire   [0:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_WID;
wire   [0:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_WUSER;
wire    grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARVALID;
wire   [31:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARADDR;
wire   [0:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARID;
wire   [31:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARLEN;
wire   [2:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARSIZE;
wire   [1:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARBURST;
wire   [1:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARLOCK;
wire   [3:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARCACHE;
wire   [2:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARPROT;
wire   [3:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARQOS;
wire   [3:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARREGION;
wire   [0:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARUSER;
wire    grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_RREADY;
wire    grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_BREADY;
wire   [31:0] grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_tmp1_out;
wire    grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_tmp1_out_ap_vld;
wire    bus_A_AWREADY;
wire    bus_A_WREADY;
reg    bus_A_ARVALID;
wire    bus_A_ARREADY;
reg   [31:0] bus_A_ARADDR;
reg   [0:0] bus_A_ARID;
reg   [31:0] bus_A_ARLEN;
reg   [2:0] bus_A_ARSIZE;
reg   [1:0] bus_A_ARBURST;
reg   [1:0] bus_A_ARLOCK;
reg   [3:0] bus_A_ARCACHE;
reg   [2:0] bus_A_ARPROT;
reg   [3:0] bus_A_ARQOS;
reg   [3:0] bus_A_ARREGION;
reg   [0:0] bus_A_ARUSER;
wire    bus_A_RVALID;
reg    bus_A_RREADY;
wire   [31:0] bus_A_RDATA;
wire    bus_A_RLAST;
wire   [0:0] bus_A_RID;
wire   [0:0] bus_A_RUSER;
wire   [1:0] bus_A_RRESP;
wire    bus_A_BVALID;
wire   [1:0] bus_A_BRESP;
wire   [0:0] bus_A_BID;
wire   [0:0] bus_A_BUSER;
wire    bus_B_AWREADY;
wire    bus_B_WREADY;
reg    bus_B_ARVALID;
wire    bus_B_ARREADY;
reg   [31:0] bus_B_ARADDR;
reg   [0:0] bus_B_ARID;
reg   [31:0] bus_B_ARLEN;
reg   [2:0] bus_B_ARSIZE;
reg   [1:0] bus_B_ARBURST;
reg   [1:0] bus_B_ARLOCK;
reg   [3:0] bus_B_ARCACHE;
reg   [2:0] bus_B_ARPROT;
reg   [3:0] bus_B_ARQOS;
reg   [3:0] bus_B_ARREGION;
reg   [0:0] bus_B_ARUSER;
wire    bus_B_RVALID;
reg    bus_B_RREADY;
wire   [31:0] bus_B_RDATA;
wire    bus_B_RLAST;
wire   [0:0] bus_B_RID;
wire   [0:0] bus_B_RUSER;
wire   [1:0] bus_B_RRESP;
wire    bus_B_BVALID;
wire   [1:0] bus_B_BRESP;
wire   [0:0] bus_B_BID;
wire   [0:0] bus_B_BUSER;
reg    bus_res_AWVALID;
wire    bus_res_AWREADY;
reg    bus_res_WVALID;
wire    bus_res_WREADY;
wire   [31:0] bus_res_WDATA;
wire    bus_res_ARREADY;
wire    bus_res_RVALID;
wire   [31:0] bus_res_RDATA;
wire    bus_res_RLAST;
wire   [0:0] bus_res_RID;
wire   [0:0] bus_res_RUSER;
wire   [1:0] bus_res_RRESP;
wire    bus_res_BVALID;
reg    bus_res_BREADY;
wire   [1:0] bus_res_BRESP;
wire   [0:0] bus_res_BID;
wire   [0:0] bus_res_BUSER;
reg    grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_ap_start_reg;
wire    ap_CS_fsm_state9;
wire  signed [31:0] sext_ln14_fu_167_p1;
wire  signed [31:0] sext_ln14_1_fu_177_p1;
wire   [31:0] sext_ln20_fu_187_p1;
reg    ap_block_state2_io;
reg   [15:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
#0 grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_ap_start_reg = 1'b0;
end

test_scalaire_test_scalaire_Pipeline_VITIS_LOOP_14_1 grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_ap_start),
    .ap_done(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_ap_done),
    .ap_idle(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_ap_idle),
    .ap_ready(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_ap_ready),
    .m_axi_bus_B_AWVALID(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWVALID),
    .m_axi_bus_B_AWREADY(1'b0),
    .m_axi_bus_B_AWADDR(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWADDR),
    .m_axi_bus_B_AWID(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWID),
    .m_axi_bus_B_AWLEN(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWLEN),
    .m_axi_bus_B_AWSIZE(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWSIZE),
    .m_axi_bus_B_AWBURST(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWBURST),
    .m_axi_bus_B_AWLOCK(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWLOCK),
    .m_axi_bus_B_AWCACHE(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWCACHE),
    .m_axi_bus_B_AWPROT(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWPROT),
    .m_axi_bus_B_AWQOS(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWQOS),
    .m_axi_bus_B_AWREGION(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWREGION),
    .m_axi_bus_B_AWUSER(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_AWUSER),
    .m_axi_bus_B_WVALID(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_WVALID),
    .m_axi_bus_B_WREADY(1'b0),
    .m_axi_bus_B_WDATA(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_WDATA),
    .m_axi_bus_B_WSTRB(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_WSTRB),
    .m_axi_bus_B_WLAST(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_WLAST),
    .m_axi_bus_B_WID(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_WID),
    .m_axi_bus_B_WUSER(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_WUSER),
    .m_axi_bus_B_ARVALID(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARVALID),
    .m_axi_bus_B_ARREADY(bus_B_ARREADY),
    .m_axi_bus_B_ARADDR(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARADDR),
    .m_axi_bus_B_ARID(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARID),
    .m_axi_bus_B_ARLEN(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARLEN),
    .m_axi_bus_B_ARSIZE(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARSIZE),
    .m_axi_bus_B_ARBURST(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARBURST),
    .m_axi_bus_B_ARLOCK(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARLOCK),
    .m_axi_bus_B_ARCACHE(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARCACHE),
    .m_axi_bus_B_ARPROT(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARPROT),
    .m_axi_bus_B_ARQOS(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARQOS),
    .m_axi_bus_B_ARREGION(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARREGION),
    .m_axi_bus_B_ARUSER(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARUSER),
    .m_axi_bus_B_RVALID(bus_B_RVALID),
    .m_axi_bus_B_RREADY(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_RREADY),
    .m_axi_bus_B_RDATA(bus_B_RDATA),
    .m_axi_bus_B_RLAST(bus_B_RLAST),
    .m_axi_bus_B_RID(bus_B_RID),
    .m_axi_bus_B_RUSER(bus_B_RUSER),
    .m_axi_bus_B_RRESP(bus_B_RRESP),
    .m_axi_bus_B_BVALID(1'b0),
    .m_axi_bus_B_BREADY(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_BREADY),
    .m_axi_bus_B_BRESP(2'd0),
    .m_axi_bus_B_BID(1'd0),
    .m_axi_bus_B_BUSER(1'd0),
    .sext_ln14_1(trunc_ln14_1_reg_217),
    .m_axi_bus_A_AWVALID(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWVALID),
    .m_axi_bus_A_AWREADY(1'b0),
    .m_axi_bus_A_AWADDR(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWADDR),
    .m_axi_bus_A_AWID(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWID),
    .m_axi_bus_A_AWLEN(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWLEN),
    .m_axi_bus_A_AWSIZE(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWSIZE),
    .m_axi_bus_A_AWBURST(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWBURST),
    .m_axi_bus_A_AWLOCK(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWLOCK),
    .m_axi_bus_A_AWCACHE(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWCACHE),
    .m_axi_bus_A_AWPROT(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWPROT),
    .m_axi_bus_A_AWQOS(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWQOS),
    .m_axi_bus_A_AWREGION(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWREGION),
    .m_axi_bus_A_AWUSER(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_AWUSER),
    .m_axi_bus_A_WVALID(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_WVALID),
    .m_axi_bus_A_WREADY(1'b0),
    .m_axi_bus_A_WDATA(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_WDATA),
    .m_axi_bus_A_WSTRB(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_WSTRB),
    .m_axi_bus_A_WLAST(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_WLAST),
    .m_axi_bus_A_WID(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_WID),
    .m_axi_bus_A_WUSER(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_WUSER),
    .m_axi_bus_A_ARVALID(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARVALID),
    .m_axi_bus_A_ARREADY(bus_A_ARREADY),
    .m_axi_bus_A_ARADDR(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARADDR),
    .m_axi_bus_A_ARID(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARID),
    .m_axi_bus_A_ARLEN(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARLEN),
    .m_axi_bus_A_ARSIZE(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARSIZE),
    .m_axi_bus_A_ARBURST(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARBURST),
    .m_axi_bus_A_ARLOCK(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARLOCK),
    .m_axi_bus_A_ARCACHE(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARCACHE),
    .m_axi_bus_A_ARPROT(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARPROT),
    .m_axi_bus_A_ARQOS(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARQOS),
    .m_axi_bus_A_ARREGION(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARREGION),
    .m_axi_bus_A_ARUSER(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARUSER),
    .m_axi_bus_A_RVALID(bus_A_RVALID),
    .m_axi_bus_A_RREADY(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_RREADY),
    .m_axi_bus_A_RDATA(bus_A_RDATA),
    .m_axi_bus_A_RLAST(bus_A_RLAST),
    .m_axi_bus_A_RID(bus_A_RID),
    .m_axi_bus_A_RUSER(bus_A_RUSER),
    .m_axi_bus_A_RRESP(bus_A_RRESP),
    .m_axi_bus_A_BVALID(1'b0),
    .m_axi_bus_A_BREADY(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_BREADY),
    .m_axi_bus_A_BRESP(2'd0),
    .m_axi_bus_A_BID(1'd0),
    .m_axi_bus_A_BUSER(1'd0),
    .sext_ln14(trunc_ln_reg_211),
    .tmp1_out(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_tmp1_out),
    .tmp1_out_ap_vld(grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_tmp1_out_ap_vld)
);

test_scalaire_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .A(A),
    .B(B),
    .res(res),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

test_scalaire_bus_A_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_BUS_A_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_BUS_A_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_BUS_A_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_BUS_A_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_BUS_A_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_BUS_A_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_BUS_A_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_BUS_A_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_BUS_A_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_BUS_A_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_BUS_A_CACHE_VALUE ))
bus_A_m_axi_U(
    .AWVALID(m_axi_bus_A_AWVALID),
    .AWREADY(m_axi_bus_A_AWREADY),
    .AWADDR(m_axi_bus_A_AWADDR),
    .AWID(m_axi_bus_A_AWID),
    .AWLEN(m_axi_bus_A_AWLEN),
    .AWSIZE(m_axi_bus_A_AWSIZE),
    .AWBURST(m_axi_bus_A_AWBURST),
    .AWLOCK(m_axi_bus_A_AWLOCK),
    .AWCACHE(m_axi_bus_A_AWCACHE),
    .AWPROT(m_axi_bus_A_AWPROT),
    .AWQOS(m_axi_bus_A_AWQOS),
    .AWREGION(m_axi_bus_A_AWREGION),
    .AWUSER(m_axi_bus_A_AWUSER),
    .WVALID(m_axi_bus_A_WVALID),
    .WREADY(m_axi_bus_A_WREADY),
    .WDATA(m_axi_bus_A_WDATA),
    .WSTRB(m_axi_bus_A_WSTRB),
    .WLAST(m_axi_bus_A_WLAST),
    .WID(m_axi_bus_A_WID),
    .WUSER(m_axi_bus_A_WUSER),
    .ARVALID(m_axi_bus_A_ARVALID),
    .ARREADY(m_axi_bus_A_ARREADY),
    .ARADDR(m_axi_bus_A_ARADDR),
    .ARID(m_axi_bus_A_ARID),
    .ARLEN(m_axi_bus_A_ARLEN),
    .ARSIZE(m_axi_bus_A_ARSIZE),
    .ARBURST(m_axi_bus_A_ARBURST),
    .ARLOCK(m_axi_bus_A_ARLOCK),
    .ARCACHE(m_axi_bus_A_ARCACHE),
    .ARPROT(m_axi_bus_A_ARPROT),
    .ARQOS(m_axi_bus_A_ARQOS),
    .ARREGION(m_axi_bus_A_ARREGION),
    .ARUSER(m_axi_bus_A_ARUSER),
    .RVALID(m_axi_bus_A_RVALID),
    .RREADY(m_axi_bus_A_RREADY),
    .RDATA(m_axi_bus_A_RDATA),
    .RLAST(m_axi_bus_A_RLAST),
    .RID(m_axi_bus_A_RID),
    .RUSER(m_axi_bus_A_RUSER),
    .RRESP(m_axi_bus_A_RRESP),
    .BVALID(m_axi_bus_A_BVALID),
    .BREADY(m_axi_bus_A_BREADY),
    .BRESP(m_axi_bus_A_BRESP),
    .BID(m_axi_bus_A_BID),
    .BUSER(m_axi_bus_A_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(bus_A_ARVALID),
    .I_ARREADY(bus_A_ARREADY),
    .I_ARADDR(bus_A_ARADDR),
    .I_ARID(bus_A_ARID),
    .I_ARLEN(bus_A_ARLEN),
    .I_ARSIZE(bus_A_ARSIZE),
    .I_ARLOCK(bus_A_ARLOCK),
    .I_ARCACHE(bus_A_ARCACHE),
    .I_ARQOS(bus_A_ARQOS),
    .I_ARPROT(bus_A_ARPROT),
    .I_ARUSER(bus_A_ARUSER),
    .I_ARBURST(bus_A_ARBURST),
    .I_ARREGION(bus_A_ARREGION),
    .I_RVALID(bus_A_RVALID),
    .I_RREADY(bus_A_RREADY),
    .I_RDATA(bus_A_RDATA),
    .I_RID(bus_A_RID),
    .I_RUSER(bus_A_RUSER),
    .I_RRESP(bus_A_RRESP),
    .I_RLAST(bus_A_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(bus_A_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(bus_A_WREADY),
    .I_WDATA(32'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd0),
    .I_BVALID(bus_A_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(bus_A_BRESP),
    .I_BID(bus_A_BID),
    .I_BUSER(bus_A_BUSER)
);

test_scalaire_bus_B_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_BUS_B_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_BUS_B_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_BUS_B_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_BUS_B_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_BUS_B_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_BUS_B_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_BUS_B_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_BUS_B_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_BUS_B_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_BUS_B_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_BUS_B_CACHE_VALUE ))
bus_B_m_axi_U(
    .AWVALID(m_axi_bus_B_AWVALID),
    .AWREADY(m_axi_bus_B_AWREADY),
    .AWADDR(m_axi_bus_B_AWADDR),
    .AWID(m_axi_bus_B_AWID),
    .AWLEN(m_axi_bus_B_AWLEN),
    .AWSIZE(m_axi_bus_B_AWSIZE),
    .AWBURST(m_axi_bus_B_AWBURST),
    .AWLOCK(m_axi_bus_B_AWLOCK),
    .AWCACHE(m_axi_bus_B_AWCACHE),
    .AWPROT(m_axi_bus_B_AWPROT),
    .AWQOS(m_axi_bus_B_AWQOS),
    .AWREGION(m_axi_bus_B_AWREGION),
    .AWUSER(m_axi_bus_B_AWUSER),
    .WVALID(m_axi_bus_B_WVALID),
    .WREADY(m_axi_bus_B_WREADY),
    .WDATA(m_axi_bus_B_WDATA),
    .WSTRB(m_axi_bus_B_WSTRB),
    .WLAST(m_axi_bus_B_WLAST),
    .WID(m_axi_bus_B_WID),
    .WUSER(m_axi_bus_B_WUSER),
    .ARVALID(m_axi_bus_B_ARVALID),
    .ARREADY(m_axi_bus_B_ARREADY),
    .ARADDR(m_axi_bus_B_ARADDR),
    .ARID(m_axi_bus_B_ARID),
    .ARLEN(m_axi_bus_B_ARLEN),
    .ARSIZE(m_axi_bus_B_ARSIZE),
    .ARBURST(m_axi_bus_B_ARBURST),
    .ARLOCK(m_axi_bus_B_ARLOCK),
    .ARCACHE(m_axi_bus_B_ARCACHE),
    .ARPROT(m_axi_bus_B_ARPROT),
    .ARQOS(m_axi_bus_B_ARQOS),
    .ARREGION(m_axi_bus_B_ARREGION),
    .ARUSER(m_axi_bus_B_ARUSER),
    .RVALID(m_axi_bus_B_RVALID),
    .RREADY(m_axi_bus_B_RREADY),
    .RDATA(m_axi_bus_B_RDATA),
    .RLAST(m_axi_bus_B_RLAST),
    .RID(m_axi_bus_B_RID),
    .RUSER(m_axi_bus_B_RUSER),
    .RRESP(m_axi_bus_B_RRESP),
    .BVALID(m_axi_bus_B_BVALID),
    .BREADY(m_axi_bus_B_BREADY),
    .BRESP(m_axi_bus_B_BRESP),
    .BID(m_axi_bus_B_BID),
    .BUSER(m_axi_bus_B_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(bus_B_ARVALID),
    .I_ARREADY(bus_B_ARREADY),
    .I_ARADDR(bus_B_ARADDR),
    .I_ARID(bus_B_ARID),
    .I_ARLEN(bus_B_ARLEN),
    .I_ARSIZE(bus_B_ARSIZE),
    .I_ARLOCK(bus_B_ARLOCK),
    .I_ARCACHE(bus_B_ARCACHE),
    .I_ARQOS(bus_B_ARQOS),
    .I_ARPROT(bus_B_ARPROT),
    .I_ARUSER(bus_B_ARUSER),
    .I_ARBURST(bus_B_ARBURST),
    .I_ARREGION(bus_B_ARREGION),
    .I_RVALID(bus_B_RVALID),
    .I_RREADY(bus_B_RREADY),
    .I_RDATA(bus_B_RDATA),
    .I_RID(bus_B_RID),
    .I_RUSER(bus_B_RUSER),
    .I_RRESP(bus_B_RRESP),
    .I_RLAST(bus_B_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(bus_B_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(bus_B_WREADY),
    .I_WDATA(32'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd0),
    .I_BVALID(bus_B_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(bus_B_BRESP),
    .I_BID(bus_B_BID),
    .I_BUSER(bus_B_BUSER)
);

test_scalaire_bus_res_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_BUS_RES_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_BUS_RES_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_BUS_RES_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_BUS_RES_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_BUS_RES_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_BUS_RES_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_BUS_RES_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_BUS_RES_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_BUS_RES_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_BUS_RES_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_BUS_RES_CACHE_VALUE ))
bus_res_m_axi_U(
    .AWVALID(m_axi_bus_res_AWVALID),
    .AWREADY(m_axi_bus_res_AWREADY),
    .AWADDR(m_axi_bus_res_AWADDR),
    .AWID(m_axi_bus_res_AWID),
    .AWLEN(m_axi_bus_res_AWLEN),
    .AWSIZE(m_axi_bus_res_AWSIZE),
    .AWBURST(m_axi_bus_res_AWBURST),
    .AWLOCK(m_axi_bus_res_AWLOCK),
    .AWCACHE(m_axi_bus_res_AWCACHE),
    .AWPROT(m_axi_bus_res_AWPROT),
    .AWQOS(m_axi_bus_res_AWQOS),
    .AWREGION(m_axi_bus_res_AWREGION),
    .AWUSER(m_axi_bus_res_AWUSER),
    .WVALID(m_axi_bus_res_WVALID),
    .WREADY(m_axi_bus_res_WREADY),
    .WDATA(m_axi_bus_res_WDATA),
    .WSTRB(m_axi_bus_res_WSTRB),
    .WLAST(m_axi_bus_res_WLAST),
    .WID(m_axi_bus_res_WID),
    .WUSER(m_axi_bus_res_WUSER),
    .ARVALID(m_axi_bus_res_ARVALID),
    .ARREADY(m_axi_bus_res_ARREADY),
    .ARADDR(m_axi_bus_res_ARADDR),
    .ARID(m_axi_bus_res_ARID),
    .ARLEN(m_axi_bus_res_ARLEN),
    .ARSIZE(m_axi_bus_res_ARSIZE),
    .ARBURST(m_axi_bus_res_ARBURST),
    .ARLOCK(m_axi_bus_res_ARLOCK),
    .ARCACHE(m_axi_bus_res_ARCACHE),
    .ARPROT(m_axi_bus_res_ARPROT),
    .ARQOS(m_axi_bus_res_ARQOS),
    .ARREGION(m_axi_bus_res_ARREGION),
    .ARUSER(m_axi_bus_res_ARUSER),
    .RVALID(m_axi_bus_res_RVALID),
    .RREADY(m_axi_bus_res_RREADY),
    .RDATA(m_axi_bus_res_RDATA),
    .RLAST(m_axi_bus_res_RLAST),
    .RID(m_axi_bus_res_RID),
    .RUSER(m_axi_bus_res_RUSER),
    .RRESP(m_axi_bus_res_RRESP),
    .BVALID(m_axi_bus_res_BVALID),
    .BREADY(m_axi_bus_res_BREADY),
    .BRESP(m_axi_bus_res_BRESP),
    .BID(m_axi_bus_res_BID),
    .BUSER(m_axi_bus_res_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(bus_res_ARREADY),
    .I_ARADDR(32'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(bus_res_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(bus_res_RDATA),
    .I_RID(bus_res_RID),
    .I_RUSER(bus_res_RUSER),
    .I_RRESP(bus_res_RRESP),
    .I_RLAST(bus_res_RLAST),
    .I_AWVALID(bus_res_AWVALID),
    .I_AWREADY(bus_res_AWREADY),
    .I_AWADDR(sext_ln20_fu_187_p1),
    .I_AWID(1'd0),
    .I_AWLEN(32'd1),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(bus_res_WVALID),
    .I_WREADY(bus_res_WREADY),
    .I_WDATA(bus_res_WDATA),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd15),
    .I_BVALID(bus_res_BVALID),
    .I_BREADY(bus_res_BREADY),
    .I_BRESP(bus_res_BRESP),
    .I_BID(bus_res_BID),
    .I_BUSER(bus_res_BUSER)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_ap_start_reg <= 1'b1;
        end else if ((grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_ap_ready == 1'b1)) begin
            grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln14_1_reg_217 <= {{B[31:2]}};
        trunc_ln1_reg_223 <= {{res[31:2]}};
        trunc_ln_reg_211 <= {{A[31:2]}};
    end
end

always @ (*) begin
    if (((bus_res_AWREADY == 1'b0) | (grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_ap_done == 1'b0))) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((bus_res_WREADY == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((bus_res_BVALID == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_io)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((bus_res_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((bus_res_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        bus_A_ARADDR = sext_ln14_fu_167_p1;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_A_ARADDR = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARADDR;
    end else begin
        bus_A_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_A_ARBURST = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARBURST;
    end else begin
        bus_A_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_A_ARCACHE = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARCACHE;
    end else begin
        bus_A_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_A_ARID = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARID;
    end else begin
        bus_A_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        bus_A_ARLEN = 32'd256;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_A_ARLEN = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARLEN;
    end else begin
        bus_A_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_A_ARLOCK = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARLOCK;
    end else begin
        bus_A_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_A_ARPROT = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARPROT;
    end else begin
        bus_A_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_A_ARQOS = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARQOS;
    end else begin
        bus_A_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_A_ARREGION = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARREGION;
    end else begin
        bus_A_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_A_ARSIZE = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARSIZE;
    end else begin
        bus_A_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_A_ARUSER = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARUSER;
    end else begin
        bus_A_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        bus_A_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_A_ARVALID = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_ARVALID;
    end else begin
        bus_A_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_A_RREADY = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_A_RREADY;
    end else begin
        bus_A_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bus_A_blk_n_AR = m_axi_bus_A_ARREADY;
    end else begin
        bus_A_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        bus_B_ARADDR = sext_ln14_1_fu_177_p1;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_B_ARADDR = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARADDR;
    end else begin
        bus_B_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_B_ARBURST = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARBURST;
    end else begin
        bus_B_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_B_ARCACHE = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARCACHE;
    end else begin
        bus_B_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_B_ARID = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARID;
    end else begin
        bus_B_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        bus_B_ARLEN = 32'd256;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_B_ARLEN = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARLEN;
    end else begin
        bus_B_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_B_ARLOCK = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARLOCK;
    end else begin
        bus_B_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_B_ARPROT = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARPROT;
    end else begin
        bus_B_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_B_ARQOS = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARQOS;
    end else begin
        bus_B_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_B_ARREGION = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARREGION;
    end else begin
        bus_B_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_B_ARSIZE = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARSIZE;
    end else begin
        bus_B_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_B_ARUSER = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARUSER;
    end else begin
        bus_B_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        bus_B_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_B_ARVALID = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_ARVALID;
    end else begin
        bus_B_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        bus_B_RREADY = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_m_axi_bus_B_RREADY;
    end else begin
        bus_B_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bus_B_blk_n_AR = m_axi_bus_B_ARREADY;
    end else begin
        bus_B_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((~((bus_res_AWREADY == 1'b0) | (grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state10))) begin
        bus_res_AWVALID = 1'b1;
    end else begin
        bus_res_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((bus_res_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        bus_res_BREADY = 1'b1;
    end else begin
        bus_res_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((bus_res_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        bus_res_WVALID = 1'b1;
    end else begin
        bus_res_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        bus_res_blk_n_AW = m_axi_bus_res_AWREADY;
    end else begin
        bus_res_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        bus_res_blk_n_B = m_axi_bus_res_BVALID;
    end else begin
        bus_res_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        bus_res_blk_n_W = m_axi_bus_res_WREADY;
    end else begin
        bus_res_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if ((~((bus_res_AWREADY == 1'b0) | (grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((bus_res_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((bus_res_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state2_io = ((bus_B_ARREADY == 1'b0) | (bus_A_ARREADY == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bus_res_WDATA = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_tmp1_out;

assign grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_ap_start = grp_test_scalaire_Pipeline_VITIS_LOOP_14_1_fu_126_ap_start_reg;

assign sext_ln14_1_fu_177_p1 = $signed(trunc_ln14_1_reg_217);

assign sext_ln14_fu_167_p1 = $signed(trunc_ln_reg_211);

assign sext_ln20_fu_187_p1 = $signed(trunc_ln1_reg_223);

endmodule //test_scalaire
